# Configuration Nylas Calendar API
# API pour synchroniser les rendez-vous avec Nylas Calendar
nylas.api.key=nyk_v0_hXkaPCqDNli0ocmacafTwhz0LMmjyPCt8fqwCTcMajIGoUWdis9HNUWeGV3VJc3J
nylas.api.url=https://api.us.nylas.com
