ALTER TABLE rendez_vous
    ADD COLUMN nom VARCHAR(100) NOT NULL AFTER id,
    ADD COLUMN prenom VARCHAR(100) NOT NULL AFTER nom;

ALTER TABLE consultation
    ADD COLUMN nom VARCHAR(100) NOT NULL AFTER id,
    ADD COLUMN prenom VARCHAR(100) NOT NULL AFTER nom;

